# Generated by Django 4.2 on 2023-04-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Univ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("univ_name", models.CharField(max_length=20, verbose_name="大学名")),
                ("faculty", models.CharField(max_length=20, verbose_name="学部名")),
                ("major", models.CharField(max_length=20, verbose_name="学科名")),
                ("campus", models.CharField(max_length=20, verbose_name="キャンパス名")),
            ],
        ),
    ]
