# Generated by Django 4.2 on 2023-04-26 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_univ"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="univ",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="accounts.univ",
            ),
        ),
    ]
