# Generated by Django 4.2 on 2023-04-26 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_univ"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=30, verbose_name="科目名")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "日"),
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        choices=[
                            (1, "1限"),
                            (2, "2限"),
                            (3, "3限"),
                            (4, "4限"),
                            (5, "5限"),
                            (6, "6限"),
                            (7, "7限"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="lessons", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "univ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="accounts.univ",
                    ),
                ),
            ],
        ),
    ]
