# Generated by Django 4.2 on 2023-05-03 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "男性"), (1, "女性"), (2, "その他"), (3, "こだわりなし")],
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1年生"),
                            (2, "2年生"),
                            (3, "3年生"),
                            (4, "4年生"),
                            (5, "こだわりなし"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upper", "自分よりも年上"),
                            ("same", "自分と同い年"),
                            ("lower", "自分よりも年下"),
                            ("whatever", "こだわりなし"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "target",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "新しい出会いのため"), (1, "単位取得のため")],
                        null=True,
                    ),
                ),
                (
                    "second_target",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "あなたと似ている人"), (1, "あなたと似ていない人")],
                        null=True,
                    ),
                ),
                (
                    "num_of_people",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search",
                        to="matching.favor",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search",
                        to="accounts.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
