# Generated by Django 4.2 on 2023-05-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="favor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searches",
                to="matching.favor",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searches",
                to="accounts.lesson",
            ),
        ),
    ]
